### ISSUE TITLE
[Bug] - Bug d'affichage sur le nom

### ISSUE THREAD

**Issue by kelbertpaul** [protoxvga/TES#12]
_Français_

**Décrivez le bug**
Bug d'affichage sur le nom : Prénom Nom Prénom Nom

**Pour reproduire**
Partout sur le header / dans la fiche utilisateur

**Comportement attendu**
Prénom Nom

**Captures d'écran**
![image](https://github.com/protoxvga/TES/assets/55586343/2020734c-ea0d-4845-a3b1-bc94767f4ca7)
![image](https://github.com/protoxvga/TES/assets/55586343/8df70482-59e3-424f-8301-b93705cbd883)

**Ordinateur (veuillez compléter les informations suivantes) :**

- OS: windows
- Navigateur chrome

**Comment by protoxvga** [comment]
Je viens de consulter la DB, tu t'es inscrit avec nom: Paul Kelbert | prénom: Paul Kelbert.
J'ai modifié la DB en dur, peut être erreur d'inattention de ta part ?
Mais en effet, l'update d'utilisateur ne fonctionne pas et fera l'objet d'une autre issue.

**Comment by kelbertpaul** [comment]
Ah oui mb, l'autocomplétion de chrome, mais ça a permis de détecter un autre bug
